import ScrollToTopButton from "@/components/ScrollToTopButton";
import Footer from "@/components/shadcn-studio/blocks/footer-component-01/footer-component-01";
import Header from "@/components/shadcn-studio/blocks/hero-section-41/header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { navigationData } from "@/data/navigationData";
import "@/styles/globals.css";

export const metadata = {
  title: "Felix Bakery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="h-screen flex flex-col pt-17.5">
            <Header navigationData={navigationData} />
            {children}
            <ScrollToTopButton />
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
