import Header from "@/components/Header";
import "../styles/globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Felix Bakery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased h-screen flex flex-col`}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
